### ISSUE TITLE
Issue; "This file does not seem to be a valid module zip" when uploading module to prestashop

### ISSUE THREAD

**Issue by tretron** [Interactivated/kiyohcustomerreview#9]
While trying to upload the ZIP file to my prestashop i get the following error: "This file does not seem to be a valid module zip"

Steps I undertook:

1. download dirrectly from this git
2. renamed the file to kiyohcustomerreview.zip (so  without the -master)
3. uploaded it to the webshop via "upload a module"
4. Gotten an error stating: "This file does not seem to be a valid module zip"

is this a known issue or are there ways to solve this?

**Comment by cowoder** [comment]
@tretron, I suspect the directory inside the archive might still have the -maser suffix and is causing the error

**Comment by tretron** [comment]
that was indeed the issue, renaming the folder inside the ZIP solved it.

thank you.
